var workExp = [{id: "1", 
					company: "Continental Automotive", 
					role: "Software engineer", 
					period: "Aug 2015 - present", 
					image: "conti.png",
					description: ["Application software system designer for high-end automotive instrument clusters for Japanese OEMs", 
									"Designed and implemented various modules of the instrument cluster such as turn hazard, seatbelt subsystem, clock module, lounge and cluster illumination, coolant temperature, and gear systems", 
									"Automated testing of modules using in-house unified Test Automation Framework (uTAS)",
									"Administered JIRA (issue management) and Confluence (documentation tool) servers to manage project related issues and documents", 
									"Used various development tools such as GHS Multi (debugger), CANoe Sim (simulation), Understand C (static code analyzer), Jenkins (automation server) and IBM DOORS (requirements management)"]},
               {id: "2", 
               		company: "National University of Singapore", 
               		role: "Research engineer", 
               		period: "Sep 2012 - Jun 2015", 
               		image: "nus.jpg",
               		description: ["Worked on a low power platform for sensing, signal processing and communications in a nano-satellite, which was launched in late 2015", 
               						"Developed novel fault tolerance mechanisms for FPGA-based MPSoC systems",
               						"Utilized various computational softwares and EDA tools including Xilinx, ModelSim and Matlab",
               						"Published 10 research articles in international peer-reviewed journals and conferences"]}, 
               {id: "3", 
               		company: "National University of Singapore", 
               		role: "Lab Teaching Assistant", 
               		period: "Jun 2010 - Jun 2012", 
               		image: "nus.jpg",
               		description: ["Instructed a class of over 40 students on C programming (obtained an average rating of 4+ on 5 for overall teaching effectiveness)",
               							"Evaluated and graded students’ codes for weekly labs and practical exams"]}, 
               {id: "4", 
               		company: "Sensor Networks and Applications Research Centre", 
               		role: "Research Intern", 
               		period: "May 2011 - Jul 2011", 
               		image: "cas.jpeg",
               		description: ["Designed a wearable micro-sensor platform and processing system", 
               			"Successfully implemented an HMI for the control of electrical appliances through human gestures",
               			"Developed a robust real-time finger gesture recognizer using the surface electromyography technique",
               			"Used signal extraction, segmentation, feature extraction and classification to implement the platform"]}, 
               {id: "5", 
               		company: "Data Storage Institute", 
           			role: "Research Intern", 
           			period: "May 2010 - Aug 2010", 
           			image: "dsi.jpg",
           			description: ["Aim of the project was to achieve robotic control through a mobile device",
           							"Successfully developed an accelerometer-based iPhone app to control a Roomba robot",
           							"Implementation involved interfacing various modules through different protocols, socket programming, PCB soldering and debugging through oscilloscope"]}];

var education = [{id: "1",
					school:"National University of Singapore", 
					subject:"Master of engineering [electrical and computer engineering]", 
					period: "Jan 2014 - Jul 2015", 
					image: "nus.jpg",
					description: ["Cumulative average point (CAP): 4.75 on 5.00", 
									"Thesis: Fault tolerant multi-processor system for nano-satellites",
									"Courses: neural networks, evolutionary computing, reconfigurable systems and multi-processor systems"]}, 
                 {id: "2",
                 	school:"National University of Singapore", 
                 	subject:"Bachelor of engineering [computer engineering]",           
                 	period: "Aug 2008 - Jul 2012", 
                 	image: "nus.jpg",
                 	description: ["Cumulative average point (CAP): 4.24 on 5.00",
                 					"2nd upper class honors", 
                 					"Specialization in embedded systems"]}];

var projects = [{id: "1",
					title: "Whatsapp statistics", 
					image: "whatsapp.jpg",
					description: "View converstation statistics from whatsapp conversations"},
               {id: "2",
               		title: "TOI Movie Scraper",
               		image: "toi.png", 
               		description: "Scrape good movie reviews from Times of India and get notified on your phone"},
               {id: "3",
               		title: "Carousell notifier", 
               		image: "carousell.png",
               		description: "Get notified immediately on items you're looking for on Carousell"},
               {id: "4",
               		title: "Marriage website", 
               		image: "marriage.jpg",
               		description: "A simple marriage website with RSVP"},
               {id: "5",
               		title: "Intel 8088 processor interrupt service", 
               		image: "8088.jpg",
               		description: "Music memory game playable over two different computers",
               		additionalInfo:["Programmed an Intel 8088 processor using assembly language",
               							"Developed an interrupt service and GUI for a music memory game playable over two different computers",
               							"Incorporated concepts such as integration of timer and programmable peripheral interfaces"]},
               {id: "6",
               		title: "Intel 8051 microprocessor", 
               		image: "8051.jpg",
               		description: "Custom implementation of the data path, ALU, and sequencer of the Intel 8051 microprocessor",
               		additionalInfo: ["Designed the RTL design of the data path, ALU, and sequencer of the Intel 8051 microprocessor",
               							"Generated a custom instruction set and built a sample application it",
               							"Implementation was done using VHDL and assembly programming on Xilinx Spartan-3A FPGA board"]},
               {id: "7",
               		title: "Real-time soccer controller using FPGAs", 
               		image: "soccer.jpg", 
               		description: "Real-time AI soccer game using Xilinx Spartan-3A FPGA boards",
               		additionalInfo: ["Designed and implemented a real-time soccer controller using Xilinx Spartan-3A FPGA boards",
               							"Developed a custom strategy for the soccer controller to intelligently play without external assistance",
               							"Utilized concepts of UART communication, multi-threading, mailboxes and semaphores"]},        
               {id: "8",
               		title: "Hardware PRESENT block cipher on FPGA", 
               		image: "cipher.jpg", 
               		description: "Custom hardware accelerated PRESENT block cipher implementation",
               		additionalInfo: ["Implemented multiple hardware versions of the PRESENT block cipher on a Spartan-3A FPGA board",
               							"Designed a custom opcode and driver to interface with the hardware module for hardware acceleration",
               							"Used various features of the FPGA such as BRAMs and LUTs for acceleration of the block cipher"]},
               {id: "9",
               		title: "Java encrypted file transfer client", 
               		image: "file.jpg", 
               		description: "DES encryption based secure file transfer client in Java",
               		additionalInfo: ["Developed a DES encryption based secure file transfer client on Java",
               							"File transfer client could handle various TCP/UDP variants including pipelined and persistent connections",
               							"Client was designed to handle file corruptions using the MD5 checksum"]},
               {id: "10",
               		title: "IVLE iOS app", 
               		image: "ivle.ico", 
               		description: "Mobile version of IVLE [student\'s education portal] for the iPad",
               		additionalInfo: ["Programmed a mobile version of IVLE [student’s education portal] using iOS Dev tools (XCode)",
               							"Synchronized workflow using source version controlling",
               							"App secured 3rd place for the <a href=\"http://blog.nus.edu.sg/citations/files/2011/08/icreate-winning-teams.pdf\ target=\"_blank\">iCreate Mobility Challenge</a> held by NUS"]},
               {id: "11",
               		title: "2D physics engine iPad game", 
               		image: "ipad.jpg", 
               		description: "Clone of angry birds game using custom physics engine",
               		additionalInfo: ["Programmed an Angry Birds clone using the iOS Dev tools (XCode)",
               							"Built a 2-D physics engine for the interaction between various objects ",
               							"Performed rigorous unit and integration testing of various components of the game"]}];


